# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hisinone-proxy.fullname" . }}
  labels:
{{ include "hisinone-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  his-username: {{ .Values.hisinone.username | b64enc | quote }}
  his-password: {{ .Values.hisinone.password | b64enc | quote }}